FROM ubuntu:14.04

RUN apt-get update \
 && apt-get install -q -y \
    apt-utils \
    apt-transport-https \
    wget \
    nano \
    git \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-pip \
    python-dev \
 && apt-get autoremove \
 && apt-get clean


RUN git clone --recursive -b stable-2.4 https://github.com/ansible/ansible \
 && cd ./ansible \
 && pip install --upgrade packaging \
 && pip install --upgrade setuptools \
 && pip install --upgrade -r ./requirements.txt \
 && make \
 && make install \
 && cd .. \
 && rm -rf ansible

RUN mkdir /tmp/ansible
WORKDIR /tmp/ansible
ADD local.yml /tmp/ansible/local.yml
ADD defaults /tmp/ansible/defaults
ADD tasks /tmp/ansible/tasks
ADD files/galaxyproject-nginx-pin-600 /tmp/ansible/

RUN ansible-playbook -i localhost, local.yml -e "@defaults/main.yml"
