- name: Add Docker repository key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  when: configure_docker

- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main' update_cache=yes
  when: configure_docker

- name: Install Docker package
  apt: pkg={{ item }} state={{ package_state }} install_recommends=no
  with_items:
    - "{{ docker_package }}"
  when: install_packages

- name: Install apparmor
  apt: pkg={{ item }} state={{ package_state }}
  with_items:
   - apparmor
   - cgroup-bin
  when: install_apparmor

- name: Allow galaxy user to run docker with sudo
  lineinfile: "dest=/etc/sudoers line='{{ galaxy_user_name }}  ALL = (root) NOPASSWD: SETENV: /usr/bin/docker'"

- name: Add Galaxy user to docker group - allowing sudoless docker usage
  user: name={{ galaxy_user_name }} groups=docker append=yes

- name: Stop Docker service
  service: name=docker state=stopped
  
- name: Set DOCKER_OPTS
  lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="--storage-driver=devicemapper -g {{ docker_storage_location }}"'

- name: Remove old Docker folder
  file: path=/var/lib/docker state=absent
  
- name: Restart the Docker service
  service: name=docker state=started
