---
- name: Prerequisites
  apt: name={{ item }} state={{ package_state }} update_cache=yes
  with_items:
    - apt-utils
    - apt-transport-https
    - ca-certificates

- name: Update APT cache
  apt: update_cache=yes

- name: Install required system packages
  apt: pkg={{ item }} state={{ package_state }} install_recommends=no
  with_items:
    - ant
    - cmake
    - curl
    - g++
    - gcc
    - gfortran
    - git
    - libffi-dev
    - liblapack-dev
    - libncurses5-dev
    - libopenblas-dev
    - libpam0g-dev
    - libpq-dev
    - libsparsehash-dev
    - make
    - nginx-extras
    - openssh-server
    - patch
    - pkg-config
    - python-boto
    - python-dev
    - python-prettytable
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - rsync
    - samtools
    - sudo
    - supervisor
    - swig
    - sysstat
    - unzip
    - wget
    - zlib1g-dev

- name: Add Slurm DRMAA package
  apt:
    pkg: slurm-drmaa-dev
    state: "{{ package_state }}"
  when: install_slurm_drmaa_lib

- name: Install packages for system maintenance
  apt: pkg={{ item }} state={{ package_state }}
  with_items:
    - atop
    - bioperl
    - ipython
    - iotop
    - htop
    - iftop
    - nmon
    - axel
    - vim
  when: install_maintainance_packages

- name: Install required system packages - 8
  apt: pkg={{ item }} state={{ package_state }}
  with_items:
    - postgresql-plpython-9.4
    - postgresql-server-dev-9.4
    - virtualenv
  when: ansible_distribution_version >= 8

- name: Clean up
  apt:
    autoclean: yes
    autoremove: yes
